/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChangeGateRouteImport } from './routes/change-gate'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as EvidenceRouteImport } from './routes/evidence'
import { Route as MaturityRouteImport } from './routes/maturity'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SystemRouteImport } from './routes/system'
import { Route as EvidenceIndexRouteImport } from './routes/evidence/index'
import { Route as EvidenceBenchmarksRouteImport } from './routes/evidence/benchmarks'
import { Route as EvidenceClaimsRouteImport } from './routes/evidence/claims'
import { Route as EvidenceProofCapsulesRouteImport } from './routes/evidence/proof-capsules'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangeGateRoute = ChangeGateRouteImport.update({
  id: '/change-gate',
  path: '/change-gate',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceRoute = EvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const MaturityRoute = MaturityRouteImport.update({
  id: '/maturity',
  path: '/maturity',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemRoute = SystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceIndexRoute = EvidenceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EvidenceRoute,
} as any)
const EvidenceBenchmarksRoute = EvidenceBenchmarksRouteImport.update({
  id: '/benchmarks',
  path: '/benchmarks',
  getParentRoute: () => EvidenceRoute,
} as any)
const EvidenceClaimsRoute = EvidenceClaimsRouteImport.update({
  id: '/claims',
  path: '/claims',
  getParentRoute: () => EvidenceRoute,
} as any)
const EvidenceProofCapsulesRoute = EvidenceProofCapsulesRouteImport.update({
  id: '/proof-capsules',
  path: '/proof-capsules',
  getParentRoute: () => EvidenceRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/change-gate': typeof ChangeGateRoute
  '/developers': typeof DevelopersRoute
  '/evidence': typeof EvidenceRouteWithChildren
  '/maturity': typeof MaturityRoute
  '/research': typeof ResearchRoute
  '/security': typeof SecurityRoute
  '/system': typeof SystemRoute
  '/evidence/benchmarks': typeof EvidenceBenchmarksRoute
  '/evidence/claims': typeof EvidenceClaimsRoute
  '/evidence/proof-capsules': typeof EvidenceProofCapsulesRoute
  '/evidence/': typeof EvidenceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/change-gate': typeof ChangeGateRoute
  '/developers': typeof DevelopersRoute
  '/maturity': typeof MaturityRoute
  '/research': typeof ResearchRoute
  '/security': typeof SecurityRoute
  '/system': typeof SystemRoute
  '/evidence/benchmarks': typeof EvidenceBenchmarksRoute
  '/evidence/claims': typeof EvidenceClaimsRoute
  '/evidence/proof-capsules': typeof EvidenceProofCapsulesRoute
  '/evidence': typeof EvidenceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/change-gate': typeof ChangeGateRoute
  '/developers': typeof DevelopersRoute
  '/evidence': typeof EvidenceRouteWithChildren
  '/maturity': typeof MaturityRoute
  '/research': typeof ResearchRoute
  '/security': typeof SecurityRoute
  '/system': typeof SystemRoute
  '/evidence/benchmarks': typeof EvidenceBenchmarksRoute
  '/evidence/claims': typeof EvidenceClaimsRoute
  '/evidence/proof-capsules': typeof EvidenceProofCapsulesRoute
  '/evidence/': typeof EvidenceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/change-gate'
    | '/developers'
    | '/evidence'
    | '/maturity'
    | '/research'
    | '/security'
    | '/system'
    | '/evidence/benchmarks'
    | '/evidence/claims'
    | '/evidence/proof-capsules'
    | '/evidence/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/change-gate'
    | '/developers'
    | '/maturity'
    | '/research'
    | '/security'
    | '/system'
    | '/evidence/benchmarks'
    | '/evidence/claims'
    | '/evidence/proof-capsules'
    | '/evidence'
  id:
    | '__root__'
    | '/'
    | '/change-gate'
    | '/developers'
    | '/evidence'
    | '/maturity'
    | '/research'
    | '/security'
    | '/system'
    | '/evidence/benchmarks'
    | '/evidence/claims'
    | '/evidence/proof-capsules'
    | '/evidence/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChangeGateRoute: typeof ChangeGateRoute
  DevelopersRoute: typeof DevelopersRoute
  EvidenceRoute: typeof EvidenceRouteWithChildren
  MaturityRoute: typeof MaturityRoute
  ResearchRoute: typeof ResearchRoute
  SecurityRoute: typeof SecurityRoute
  SystemRoute: typeof SystemRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-gate': {
      id: '/change-gate'
      path: '/change-gate'
      fullPath: '/change-gate'
      preLoaderRoute: typeof ChangeGateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence': {
      id: '/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof EvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maturity': {
      id: '/maturity'
      path: '/maturity'
      fullPath: '/maturity'
      preLoaderRoute: typeof MaturityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system': {
      id: '/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence/': {
      id: '/evidence/'
      path: '/'
      fullPath: '/evidence/'
      preLoaderRoute: typeof EvidenceIndexRouteImport
      parentRoute: typeof EvidenceRoute
    }
    '/evidence/benchmarks': {
      id: '/evidence/benchmarks'
      path: '/benchmarks'
      fullPath: '/evidence/benchmarks'
      preLoaderRoute: typeof EvidenceBenchmarksRouteImport
      parentRoute: typeof EvidenceRoute
    }
    '/evidence/claims': {
      id: '/evidence/claims'
      path: '/claims'
      fullPath: '/evidence/claims'
      preLoaderRoute: typeof EvidenceClaimsRouteImport
      parentRoute: typeof EvidenceRoute
    }
    '/evidence/proof-capsules': {
      id: '/evidence/proof-capsules'
      path: '/proof-capsules'
      fullPath: '/evidence/proof-capsules'
      preLoaderRoute: typeof EvidenceProofCapsulesRouteImport
      parentRoute: typeof EvidenceRoute
    }
  }
}

interface EvidenceRouteChildren {
  EvidenceBenchmarksRoute: typeof EvidenceBenchmarksRoute
  EvidenceClaimsRoute: typeof EvidenceClaimsRoute
  EvidenceProofCapsulesRoute: typeof EvidenceProofCapsulesRoute
  EvidenceIndexRoute: typeof EvidenceIndexRoute
}

const EvidenceRouteChildren: EvidenceRouteChildren = {
  EvidenceBenchmarksRoute: EvidenceBenchmarksRoute,
  EvidenceClaimsRoute: EvidenceClaimsRoute,
  EvidenceProofCapsulesRoute: EvidenceProofCapsulesRoute,
  EvidenceIndexRoute: EvidenceIndexRoute,
}

const EvidenceRouteWithChildren = EvidenceRoute._addFileChildren(
  EvidenceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChangeGateRoute: ChangeGateRoute,
  DevelopersRoute: DevelopersRoute,
  EvidenceRoute: EvidenceRouteWithChildren,
  MaturityRoute: MaturityRoute,
  ResearchRoute: ResearchRoute,
  SecurityRoute: SecurityRoute,
  SystemRoute: SystemRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
